name: deploy to lambda
on: [push]

# Specify what jobs to run
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env: #Setup environmental variables for serverless deployment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Use github defaut action to trigger action in this repo. Mandatory
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
      - uses: actions/checkout@v1

      - name: Create env file
        run: | 
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF

      - name: npm install dependencies
        run: npm install

      - name: Serverless
        uses: serverless/github-action@master
        with:
          args: deploy
